// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: testdata/proto/proto1.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	plugin "github.com/medianexapp/plugin_api/plugin"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMethod    *plugin.AuthMethod     `protobuf:"bytes,1,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProto) Reset() {
	*x = TestProto{}
	mi := &file_testdata_proto_proto1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto) ProtoMessage() {}

func (x *TestProto) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_proto1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto.ProtoReflect.Descriptor instead.
func (*TestProto) Descriptor() ([]byte, []int) {
	return file_testdata_proto_proto1_proto_rawDescGZIP(), []int{0}
}

func (x *TestProto) GetAuthMethod() *plugin.AuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return nil
}

type TestTimeStamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTimeStamp) Reset() {
	*x = TestTimeStamp{}
	mi := &file_testdata_proto_proto1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTimeStamp) ProtoMessage() {}

func (x *TestTimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_proto1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTimeStamp.ProtoReflect.Descriptor instead.
func (*TestTimeStamp) Descriptor() ([]byte, []int) {
	return file_testdata_proto_proto1_proto_rawDescGZIP(), []int{1}
}

func (x *TestTimeStamp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TestAny struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Any           *anypb.Any             `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAny) Reset() {
	*x = TestAny{}
	mi := &file_testdata_proto_proto1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAny) ProtoMessage() {}

func (x *TestAny) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_proto1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAny.ProtoReflect.Descriptor instead.
func (*TestAny) Descriptor() ([]byte, []int) {
	return file_testdata_proto_proto1_proto_rawDescGZIP(), []int{2}
}

func (x *TestAny) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

var File_testdata_proto_proto1_proto protoreflect.FileDescriptor

const file_testdata_proto_proto1_proto_rawDesc = "" +
	"\n" +
	"\x1btestdata/proto/proto1.proto\x12\btestdata\x1a\x13plugin/plugin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x17validate/validate.proto\"J\n" +
	"\tTestProto\x12=\n" +
	"\vauth_method\x18\x01 \x01(\v2\x12.plugin.AuthMethodB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"authMethod\"S\n" +
	"\rTestTimeStamp\x12B\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\ttimestamp\";\n" +
	"\aTestAny\x120\n" +
	"\x03any\x18\x01 \x01(\v2\x14.google.protobuf.AnyB\b\xfaB\x05\xa2\x01\x02\b\x01R\x03anyB'Z%github.com/pbm-org/pbm/testdata/protob\x06proto3"

var (
	file_testdata_proto_proto1_proto_rawDescOnce sync.Once
	file_testdata_proto_proto1_proto_rawDescData []byte
)

func file_testdata_proto_proto1_proto_rawDescGZIP() []byte {
	file_testdata_proto_proto1_proto_rawDescOnce.Do(func() {
		file_testdata_proto_proto1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_proto_proto1_proto_rawDesc), len(file_testdata_proto_proto1_proto_rawDesc)))
	})
	return file_testdata_proto_proto1_proto_rawDescData
}

var file_testdata_proto_proto1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_testdata_proto_proto1_proto_goTypes = []any{
	(*TestProto)(nil),             // 0: testdata.TestProto
	(*TestTimeStamp)(nil),         // 1: testdata.TestTimeStamp
	(*TestAny)(nil),               // 2: testdata.TestAny
	(*plugin.AuthMethod)(nil),     // 3: plugin.AuthMethod
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_testdata_proto_proto1_proto_depIdxs = []int32{
	3, // 0: testdata.TestProto.auth_method:type_name -> plugin.AuthMethod
	4, // 1: testdata.TestTimeStamp.timestamp:type_name -> google.protobuf.Timestamp
	5, // 2: testdata.TestAny.any:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_testdata_proto_proto1_proto_init() }
func file_testdata_proto_proto1_proto_init() {
	if File_testdata_proto_proto1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_proto_proto1_proto_rawDesc), len(file_testdata_proto_proto1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_proto_proto1_proto_goTypes,
		DependencyIndexes: file_testdata_proto_proto1_proto_depIdxs,
		MessageInfos:      file_testdata_proto_proto1_proto_msgTypes,
	}.Build()
	File_testdata_proto_proto1_proto = out.File
	file_testdata_proto_proto1_proto_goTypes = nil
	file_testdata_proto_proto1_proto_depIdxs = nil
}
