// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: testdata/proto/proto1.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestProtoMultiError, or nil
// if none found.
func (m *TestProto) ValidateAll() error {
	return m.validate(true)
}

func (m *TestProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetAuthMethod() == nil {
		err := TestProtoValidationError{
			field:  "AuthMethod",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetAuthMethod()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestProtoValidationError{
					field:  "AuthMethod",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestProtoValidationError{
					field:  "AuthMethod",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthMethod()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestProtoValidationError{
				field:  "AuthMethod",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TestProtoMultiError(errors)
	}

	return nil
}

// TestProtoMultiError is an error wrapping multiple validation errors returned
// by TestProto.ValidateAll() if the designated constraints aren't met.
type TestProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestProtoMultiError) AllErrors() []error { return m }

// TestProtoValidationError is the validation error returned by
// TestProto.Validate if the designated constraints aren't met.
type TestProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestProtoValidationError) ErrorName() string { return "TestProtoValidationError" }

// Error satisfies the builtin error interface
func (e TestProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestProtoValidationError{}

// Validate checks the field values on TestTimeStamp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestTimeStamp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestTimeStamp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestTimeStampMultiError, or
// nil if none found.
func (m *TestTimeStamp) ValidateAll() error {
	return m.validate(true)
}

func (m *TestTimeStamp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTimestamp() == nil {
		err := TestTimeStampValidationError{
			field:  "Timestamp",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TestTimeStampMultiError(errors)
	}

	return nil
}

// TestTimeStampMultiError is an error wrapping multiple validation errors
// returned by TestTimeStamp.ValidateAll() if the designated constraints
// aren't met.
type TestTimeStampMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestTimeStampMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestTimeStampMultiError) AllErrors() []error { return m }

// TestTimeStampValidationError is the validation error returned by
// TestTimeStamp.Validate if the designated constraints aren't met.
type TestTimeStampValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestTimeStampValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestTimeStampValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestTimeStampValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestTimeStampValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestTimeStampValidationError) ErrorName() string { return "TestTimeStampValidationError" }

// Error satisfies the builtin error interface
func (e TestTimeStampValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestTimeStamp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestTimeStampValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestTimeStampValidationError{}

// Validate checks the field values on TestAny with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestAny) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestAny with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TestAnyMultiError, or nil if none found.
func (m *TestAny) ValidateAll() error {
	return m.validate(true)
}

func (m *TestAny) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetAny() == nil {
		err := TestAnyValidationError{
			field:  "Any",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if a := m.GetAny(); a != nil {

	}

	if len(errors) > 0 {
		return TestAnyMultiError(errors)
	}

	return nil
}

// TestAnyMultiError is an error wrapping multiple validation errors returned
// by TestAny.ValidateAll() if the designated constraints aren't met.
type TestAnyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestAnyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestAnyMultiError) AllErrors() []error { return m }

// TestAnyValidationError is the validation error returned by TestAny.Validate
// if the designated constraints aren't met.
type TestAnyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestAnyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestAnyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestAnyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestAnyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestAnyValidationError) ErrorName() string { return "TestAnyValidationError" }

// Error satisfies the builtin error interface
func (e TestAnyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestAny.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestAnyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestAnyValidationError{}
